name: Gradle Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - run: chmod +x gradlew

      - name: Run tests and capture output
        id: test_run
        run: |
          TEST_OUTPUT=$(./gradlew test --no-daemon --quiet 2>&1; echo "EXIT_CODE=$?")
          echo "TEST_OUTPUT<<EOF" >> $GITHUB_ENV
          echo "$TEST_OUTPUT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Generate Test Summary
        if: always()
        run: |
          echo "Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Используем сохраненный вывод
          if echo "$TEST_OUTPUT" | grep -q "BUILD SUCCESSFUL"; then
            echo "All tests passed!" >> $GITHUB_STEP_SUMMARY
            echo "Everything is working perfectly!" >> $GITHUB_STEP_SUMMARY
          else
            echo "Some tests failed!" >> $GITHUB_STEP_SUMMARY
            echo "Check the test logs for details." >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Test Statistics:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "$TEST_OUTPUT" | grep -E "(tests|PASSED|FAILED|SKIPPED|BUILD)" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
