name: Gradle Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - run: chmod +x gradlew
      - run: ./gradlew test --no-daemon --console=plain

      - name: Create Simple Summary
        if: always()
        run: |
          echo "Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Tests completed successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "View the test output above for detailed results." >> $GITHUB_STEP_SUMMARY